name = "placeholder-app-name"
main = "src/main.tsx"
compatibility_date = "2024-01-01"


[[kv_namespaces]]
binding = "PLACEHOLDER_KV_NAMESPACE"
id = "4b6f90b7b1b54b12bc7dcbdf4dd41d42"

[assets]
directory = "./dist"
not_found_handling = "404-page"
# will serve dist/404.html (which copies over from public/404.html)

[build]
command = "npm run build"
